version: '3.7'

services:
    slim:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - "BUILD_ARGUMENT_ENV=dev"
                - "BUILD_ARGUMENT_DEBUG_ENABLED=false"
        command: 'php -S 0.0.0.0:${APPLICATION_PORT:-8080} -t public/'
        ports:
            - '${APPLICATION_PORT:-8080}:8080'
        networks:
            - saba_idea
        volumes:
            - .:/var/www/html
            - logs:/var/www/logs
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './docker/mysql:/var/lib/mysql'
        networks:
            - saba_idea
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - './docker/redis:/data'
        networks:
            - saba_idea
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

networks:
    saba_idea:
        driver: bridge
volumes:
    logs:
        driver: local